### ISSUE TITLE
Archrisks : error: package 'is' was not found

### ISSUE THREAD

**Issue by nobicycle** [Fincer/archtools#1]
![Screenshot_2024-03-25_08-55-04](https://github.com/Fincer/archtools/assets/1372447/6129bf30-6f5c-4d34-8d10-ca137e9bd683)

Thanks for archtools. Please see screenshot

**Comment by nobicycle** [comment]
$ uname -a
Linux tower 6.6.19-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Mar  1 18:16:16 UTC 2024 x86_64 GNU/Linux
[user@tower tools]$ pacman -V

 .--.                  Pacman v6.0.2 - libalpm v13.0.2
/ _.-' .-.  .-.  .-.   Copyright (C) 2006-2021 Pacman Development Team
\  '-. '-'  '-'  '-'   Copyright (C) 2002-2006 Judd Vinet

**Comment by Fincer** [comment]
Hey there,

Thanks for raising this issue. I am sorry I respond quite late.

The archrisks script broke due to changes in Arch Linux audit tool output which the script could not parse. I have updated `archrisks` script which fixes the issue.
